Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://next.cblp.su"
  copyright: © 2013—2015 <a href="http://cblp.su/">Yuriy Syrovetskiy</a>
  #analytics: UA-YOURCODE

  notesOnAPage: 20
  noteSuggestSize: 10

Development:
  <<: *defaults
  approot: "http://localhost:3000"

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  <<: *defaults
