Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://localhost:3000"
  copyright: © 2013—2014 <a href="http://cblp.su/">Yuriy Syrovetskiy</a>
  #analytics: UA-YOURCODE

  notesOnAPage: 20
  noteSuggestSize: 10

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  #approot: "http://www.example.com"
  <<: *defaults
