Default: &defaults
  database: Apoint.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: Apoint_test.sqlite3
  <<: *defaults

Staging:
  database: Apoint_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: Apoint_production.sqlite3
  poolsize: 100
  <<: *defaults
