Default: &defaults
  user: apoint
  password: Apoint
  host: localhost
  port: 5432
  database: apoint
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: apoint_test
  <<: *defaults

Staging:
  database: apoint_staging
  poolsize: 100
  <<: *defaults

Production:
  database: apoint_production
  poolsize: 100
  <<: *defaults
