Default: &defaults
  database: yesod-boilerplate.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: yesod-boilerplate_test.sqlite3
  <<: *defaults

Staging:
  database: yesod-boilerplate_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: yesod-boilerplate_production.sqlite3
  poolsize: 100
  <<: *defaults
